#!/bin/bash

# By abxh (github)

# you will need to copy the following rules to /etc/udev/rules.d/90-backlight.rules
: '
ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"
ACTION=="add", SUBSYSTEM=="leds", RUN+="/bin/chgrp video /sys/class/leds/%k/brightness"
ACTION=="add", SUBSYSTEM=="leds", RUN+="/bin/chmod g+w /sys/class/leds/%k/brightness"
'
# and add yourself to the `video` user group.

# Or make `light` or `brightnessctl` do the work of modifying the brightness and
# just call the code in notify (providing a brightness value yourself).

tag="string:x-dunst-stack-tag:brightness"
path="/sys/class/backlight/amdgpu_bl1"

icon="/home/$USER/.local/share/icons/Gruvbox-Material-Dark-OneColored/16x16/actions/brightnesssettings.svg"

raw_val=$(< $path/brightness)
min_val=0
max_val=$(< $path/max_brightness)

bar_color="#d5c4a1"

notify() {
    val=$((raw_val * 100 / 255))
    dunstify -h int:value:$val\
	     -h string:hlcolor:$bar_color\
	     -h $tag\
	     -u low\
	     -i "$icon"\
	     "Brightness:"\
	     "$raw_val"
}

case "$1" in
--inc|-i)
    new_val=$((raw_val + $2))
    raw_val=$((new_val < max_val ? new_val : max_val ))
    echo $raw_val > $path/brightness
    notify
    ;;
--dec|-d)
    new_val=$((raw_val - $2))
    raw_val=$((new_val > min_val ? new_val : min_val ))
    echo $raw_val > $path/brightness
    notify
    ;;
--get|-g)
    echo $raw_val
    ;;
*)
    echo "Usage: [SCRIPT] [COMMAND] [VALUE]"
    echo "Commands:"
    echo "  --inc/-i:			Increase brightness by raw value."
    echo "  --dec/-d:			Decrease brightness by raw value."
    echo "  --get/-g:			Get brightness by raw value."
    ;;
esac
