#!/usr/bin/env bash

tag="string:x-dunst-stack-tag:key"
icon="/home/$USER/.local/share/icons/Gruvbox-Material-Dark-OneColored/16x16/devices/input-keyboard.svg"

dunstify -h $tag \
	-i "$icon" \
	"Keyboard Layout:" \
	"$(xkb-switch)"
