#!/usr/bin/env bash

res=$(echo \
"lock
exit
poweroff
reboot
suspend" \
| rofi -dmenu -p "system")

which systemctl >/dev/null 2>&1
if [ "$?" -eq 0 ]; then
    login_manager="systemctl"
else
    login_manager="loginctl"
fi

case $res in
"lock")
    ~/.scripts/i3lock_run;;
"exit")
    for window in $(xdotool search --onlyvisible --name ".*"); do
      xdotool windowfocus $window
      xdotool key --window $window alt+F4 # try gently closing
    done
    bspc quit || i3-msg exit;;
"poweroff")
    $login_manager poweroff;;
"reboot")
    $login_manager reboot;;
"suspend")
    $login_manager suspend;;
esac 
