#!/usr/bin/env bash

res=$(echo \
"lock
exit
poweroff
reboot
suspend" \
| rofi -dmenu -p "system")

which loginctl &>/dev/null
if [ "$?" -eq 0 ]; then
    login_manager="loginctl"
else
    login_manager="systemctl"
fi

case $res in
"lock")
    sleep 0.5;
    ~/.scripts/i3lock_launch;;
"exit")
    bspc quit;;
"poweroff")
    $login_manager poweroff;;
"reboot")
    $login_manager reboot;;
"suspend")
    $login_manager suspend;;
esac 
