#!/usr/bin/env bash

icon_theme_path="/home/$USER/.local/share/icons/Gruvbox-Material-Dark-OneColored"

path="/sys/class/backlight/amdgpu_bl1"
icon="$icon_theme_path/16x16/actions/brightnesssettings.svg"

tag="string:x-dunst-stack-tag:brightness"

bar_color="#d4be98"

val=$(brightnessctl g)
max=$(brightnessctl max)
per=$(($val * 100 / $max))

dunstify \
	-h $tag \
	-h int:value:$per \
	-h string:hlcolor:$bar_color \
	-i "$icon" \
	"Brightness:" \
	"$per%"
