#!/usr/bin/env bash

sink_name="$1"
sink_name=${sink_name:-"@DEFAULT_SINK@"}

vol_max=153

bar_color="#d4be98"
muted_bar_color="$bar_color"70

muted=$(pactl get-sink-mute $sink_name | awk '{print $2}')
volume=$(pactl get-sink-volume $sink_name | awk '{print $5}' | cut -d '%' -f 1)

icon_theme_path="/home/$USER/.local/share/icons/Gruvbox-Material-Dark-OneColored"

tag="string:x-dunst-stack-tag:sink"
icon_path="$icon_theme_path/16x16/panel/"

if [[ "$muted" == "yes" ]]; then
	icon=$icon_path'audio-volume-muted.svg'
	bar_color=$muted_bar_color
else
	if [[ "$volume" -lt 34 ]]; then
		icon=$icon_path'audio-volume-low.svg'
	elif [[ "$volume" -lt 67 ]]; then
		icon=$icon_path'audio-volume-medium.svg'
	else
		icon=$icon_path'audio-volume-high.svg'
	fi
fi

dunstify -h int:value:$(($volume * 100 / $vol_max)) \
	-h string:hlcolor:$bar_color \
	-h $tag \
	-i "$icon" \
	"Volume:" \
	"$volume%"
