#!/usr/bin/env bash

source_name="$1"
source_name=${source_name:-"@DEFAULT_SOURCE@"}

icon_theme_path="/home/$USER/.local/share/icons/Gruvbox-Material-Dark-OneColored"

tag="string:x-dunst-stack-tag:source"
icon_path="$icon_theme_path/16x16/panel/"

int32_max=2147483647
id=$(($(cksum <<< $tag | awk '{print $1}') % int32_max)) # bugfix icon doesn't change if dunst notification isn't fully closed

vol_max=153

bar_color="#d4be98"
muted_bar_color="$bar_color"70

muted=$(pactl get-source-mute $source_name | awk '{print $2}')

if [ $muted == "yes" ]; then
	icon=$icon_path'audio-input-microphone-muted.svg'
	notif_desc="Muted"
else
	icon=$icon_path'audio-input-microphone-none-panel.svg'
	notif_desc="Unmuted"
fi

dunstify \
	-r $id -h $tag \
	-i "$icon" \
	"Microphone" \
	"$notif_desc"
