#!/usr/bin/env bash

tag="string:x-dunst-stack-tag:updates"
icon="/home/$USER/.local/share/icons/Gruvbox-Material-Dark-OneColored/16x16/panel/updates-notifier.svg"
icon_alt="/home/$USER/.local/share/icons/Gruvbox-Material-Dark-OneColored/16x16/panel/updates-notifier-inactive.svg"

while ! ping -c 1 -n 1.1.1.1 &>/dev/null; do
	sleep 10
done

# arch
# count=$(checkupdates | wc -l)
# count_aur=$(paru -Qau | wc -l)
#
# if ((count == 0 && count_aur == 0)); then
# 	count='no'
# 	icon=$icon_alt
# else
# 	count="$count+$count_aur"
# fi

# void
count=$(xbps-install --memory-sync --dry-run --update | grep -Fe update -e install | wc -l)

dunstify \
	-h $tag \
	-i "$icon" \
	-t 12000 \
	"Updates:" \
	"$count updates"
