#!/usr/bin/env bash

tag="string:x-dunst-stack-tag:source"
icon="/home/$USER/.local/share/icons/Gruvbox-Material-Dark-OneColored/16x16/panel/updates-notifier.svg"
icon_alt="/home/$USER/.local/share/icons/Gruvbox-Material-Dark-OneColored/16x16/panel/updates-notifier-inactive.svg"

while ! ping -c 1 -n 1.1.1.1 &>/dev/null; do
	sleep 10;
done

count=$(checkupdates | wc -l)

if (( count == 0 )); then
	count='no'
	icon=$icon_alt
fi

dunstify \
	-h $tag \
	-i "$icon" \
	"Updates:" \
	"$count updates"
