#!/usr/bin/env bash

# window rules: {{{
win_width=$((1920 * 2 / 5))
win_height=$((1080 * 3 / 5))
rule_medium_wo_float="center=true rectangle=$win_width""x""$win_height+0+0"
rule_medium="state=floating $rule_medium_wo_float"

bspc rule -a Lxappearance $rule_medium
bspc rule -a Pavucontrol $rule_medium
bspc rule -a Arandr $rule_medium
bspc rule -a Nm-connection-editor $rule_medium
# bspc rule -a kitty $rule_medium_wo_float
# bspc rule -a kitty-float $rule_medium
bspc rule -a alacritty $rule_medium_wo_float
bspc rule -a alacritty-float $rule_medium
bspc rule -a Thunar $rule_medium_wo_float
#bspc rule -a *:*:"Select file to open" $rule_medium #todo: rewrite properly
# }}}

# startup: {{{
# at start:
[ "$1" -eq 0 ] && xsetroot -cursor_name left_ptr &
[ "$1" -eq 0 ] && redshift -l "$(cat ~/.redshift-coord)" >/dev/null &
[ "$1" -eq 0 ] && xset s 600 600 dpms 0 0 660 &
[ "$1" -eq 0 ] && xss-lock -- ~/.scripts/i3lock_launch &
[ "$1" -eq 0 ] && caffeine &
[ "$1" -eq 0 ] && pulseaudio & # void linux specific
[ "$1" -eq 0 ] && picom &
[ "$1" -eq 0 ] && udiskie --no-automount --no-notify --tray &
[ "$1" -eq 0 ] && nm-applet &
[ "$1" -eq 0 ] && /usr/libexec/polkit-gnome-authentication-agent-1 &
# [ "$1" -eq 0 ] && /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
[ "$1" -eq 0 ] && ~/.config/dunst/dunstify/bat_notif_run &
# [ "$1" -eq 0 ] && kitty --title 'todo' -e ~/.scripts/todo &
[ "$1" -eq 0 ] && alacritty --title 'todo' -e ~/.scripts/todo &

# each successive restart:
[ "$1" -gt 0 ] && ~/.config/dunst/dunstify/restarted_notif bspwm &

# every restart:
( pkill -SIGKILL -x sxhkd; sxhkd >/dev/null &)
(hsetroot -cover ~/Pictures/wallpapers/wallhaven-pkp1vp.png >/dev/null;
 pkill -SIGKILL -x polybar; polybar --log=warning >/dev/null &)
~/.config/dunst/dunstify/updates_notif &

# setup monitors
for monitor in $(bspc query -M); do
	bspc monitor "$monitor" -d 1 2 3 4 5 6 7 8 9 10
done
# }}}

# setup options: {{{
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

highlight_color="#d4be98"
bspc config focused_border_color $highlight_color
bspc config active_border_color $highlight_color
bspc config presel_feedback_color $highlight_color
bspc config border_width 2

bspc config window_gap 10
bspc config top_padding -10
bspc config top_monocle_padding 10

bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
#bspc config click_to_focus any
bspc config pointer_follows_monitor true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
# }}}

# vim: fdm=marker
