#!/bin/sh

# By abxh (github)

# Using a alternative i3blocks script instead to perform the
# same function. It's a bit more hacky, but it does not use
# any explicit while-sleep loop and instead depends on i3blocks
# to call it.

lock="/tmp/dunstify_bat.lock"
tag="string:x-dunst-stack-tag:battery"
theme="Gruvbox-Material-Dark-OneColored"
icon="/usr/share/icons/$theme/16x16/panel/battery-010.svg"

while true
do
capacity=$(cat /sys/class/power_supply/BAT0/capacity)
ac_state=$(cat /sys/class/power_supply/AC/online)

if [[ "$capacity" -le 60 && "$ac_state" == "0" ]] ; then
    dunstify -h $tag \
	     -u critical \
	     -i "$icon" \
	     "Warning" \
	     "Battery is getting low!"
    sleep 9
fi

echo "$capacity"
sleep 1
done
