#!/bin/sh

# By abxh (github)

sink_name="@DEFAULT_SINK@"
source_name="@DEFAULT_SOURCE@"

icon_path='/usr/share/icons/Gruvbox-Material-Dark-OneColored/16x16/panel/'

sink_tag="string:x-dunst-stack-tag:sink"
source_tag="string:x-dunst-stack-tag:source"

vol_max=153

bar_color="#d4be98"

function sink_notification {
	sink_muted=$(pactl get-sink-mute $sink_name | awk '{print $2}')
	sink_volume=$(pactl get-sink-volume $sink_name | awk '{print $5}' | cut -d '%' -f 1)

        if [[ "$sink_muted" == "yes" ]] ; then
                sink_icon=$icon_path'audio-volume-muted.svg'
		bar_color="$bar_color"70
        else
                if [[ "$sink_volume" -lt 34 ]] ; then
                        sink_icon=$icon_path'audio-volume-low.svg'
                elif [[ "$sink_volume" -lt 67 ]] ; then
                        sink_icon=$icon_path'audio-volume-medium.svg'
                else
                        sink_icon=$icon_path'audio-volume-high.svg'
                fi
        fi

	dunstify -h int:value:$(( $sink_volume*100/$vol_max)) \
		 -h string:hlcolor:$bar_color \
                 -u low \
                 -h $sink_tag \
                 -i "$sink_icon" \
                 "Volume:" \
                 "$sink_volume%"
}

function source_notification {
	source_muted=$(pactl get-source-mute $source_name | awk '{print $2}')

	if [ $source_muted == "yes" ] ; then
		source_icon=$icon_path'audio-input-microphone-muted.svg'
		notif_desc="Muted"
	else
		source_icon=$icon_path'audio-input-microphone-none-panel.svg'
		notif_desc="Unmuted"
	fi

	dunstify -u low \
		 -h $source_tag \
		 -i "$source_icon" \
		 "Microphone" \
		 "$notif_desc"
}

case "$1" in
--inc|-i)
	sink_volume=$(pactl get-sink-volume $sink_name | awk '{print $5}' | cut -d '%' -f 1)
	[[ "$((sink_volume+$2))" -lt $vol_max ]] && pactl set-sink-volume $sink_name +$2% || pactl set-sink-volume $sink_name $vol_max%
	sink_notification
	;;
--dec|-d)
	pactl set-sink-volume $sink_name -$2%
	sink_notification
	;;
--sink_toggle|-t)
	pactl set-sink-mute $sink_name toggle
	sink_notification
	;;
--sink_mute|-m)
	pactl set-sink-mute $sink_name true
	;;
--source_toggle|-y)
	pactl set-source-mute $source_name toggle
	source_notification
	;;
--source_mute|-n)
	pactl set-source-mute $source_name true
	;;
*)
	echo "Usage: [SCRIPT] [COMMAND] [VALUE]"
	echo "Commands:"
	echo "  --inc/-i:			Increase speaker's volume by value (%)."
	echo "  --dec/-d:			Decrease speaker's volume by value (%)."
	echo "  --sink_toggle/-t:		Mute/unmute speaker."
	echo "  --sink_mute/-m:		Mute speaker."
	echo "  --source_toggle/-y:		Mute/unmute microphone."
	echo "  --source_mute/-n:		Mute microphone."
	;;
esac
