#!/usr/bin/env sh

# originally from:
# https://github.com/vivien/i3blocks-contrib/blob/master/calendar/calendar

# edited by abxh

WIDTH=${WIDTH:-200}
HEIGHT=${HEIGHT:-200}
DATEFMT=${DATEFMT:-"+%a %d.%m.%Y %H:%M:%S"}
SHORTFMT=${SHORTFMT:-"+%H:%M:%S"}

case "$BLOCK_BUTTON" in
  1|2|3)

	# the position of the upper left corner of the popup
	posX=1590
	posY=780

	pgrep -x 'yad' > /dev/null && pkill 'yad'|| i3-msg -q \
	"exec yad --calendar \
        --width=$WIDTH --height=$HEIGHT \
	    --undecorated --fixed \
	    --close-on-unfocus --no-buttons \
	    --posx=$posX --posy=$posY \
	    > /dev/null"
esac
echo "$LABEL$(date "$DATEFMT") "
echo "$LABEL$(date "$SHORTFMT") "
