#!/usr/bin/env bash

wait_for_connection() {
	while ! ping -c 1 -n 1.1.1.1 &>/dev/null; do
		echo "waiting for connection..." 1>&2
		sleep 10
	done
}

wait_for_connection

COUNT=$([ -z "$UPDATES_FILE" ] && echo -1 || eval "$UPDATES_FILE" | wc -l)

if ((COUNT == 0)); then
	COUNT='no'
fi

echo $LABEL$COUNT updates
