#!/usr/bin/python

# Script, which prints the focused i3 window title to stdout.

# requires:
# - python-i3ipc

from i3ipc import Connection

def get_focused_window_title(ipc):
    return ipc.get_tree().find_focused().window_title

def main():
    ipc = Connection()
    title = get_focused_window_title(ipc)
    if title is not None:
        print(title[:50] + ' ... ' + title[-50:] if len(title) > 105 else title)
    else:
        print('')

if __name__ == "__main__":
    main()
