#!/usr/bin/env python3

# requires:
# - python-i3ipc

from i3ipc import Connection

ipc = Connection()
title = ipc.get_tree().find_focused().window_title
if title is not None:
    print(title[:50] + " ... " + title[-50:] if len(title) > 105 else title)
else:
    print("")
