#!/usr/bin/env python3

# requires:
# - python-i3ipc

import sys

from i3ipc import Connection, Event

def update_title(ipc):
    title = ipc.get_tree().find_focused().window_title
    if title is not None:
        if title == "stalonetray":
            return
        print(title[:50] + "…" + title[-50:] if len(title) > 101 else title)
    else:
        print("")
    sys.stdout.flush()

def on_window_change(ipc, e):
    if e.change in ("focus", "close", "title"):
        update_title(ipc)

def on_workspace_change(ipc, e):
    if e.change == "focus":
        update_title(ipc)

ipc = Connection()
update_title(ipc)
ipc.on(Event.WINDOW, on_window_change)
ipc.on(Event.WORKSPACE, on_workspace_change)
ipc.main()

