#!/usr/bin/env python3

# requires:
# - i3blocks
# - python-i3ipc

from i3ipc import Connection, Event
import subprocess

SIGNAL = 10

def update_title():
    subprocess.run(["pkill", "-SIGRTMIN+" + str(SIGNAL), "i3blocks"])

def on_window_change(ipc, e):
    if e.change in ["focus", "close", "title"]:
        update_title()

def on_workspace_change(ipc, e):
    if e.change == "focus":
        update_title()

update_title()

ipc = Connection()
ipc.on(Event.WINDOW, on_window_change)
ipc.on(Event.WORKSPACE, on_workspace_change)
ipc.main()
